name: AutoCoder Workflow

# Trigger workflow on new, reopened, and labeled issues
on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate_code:
    # Run this job only if the issue has or was given the label 'autocoder-bot'
    if: >
      github.event.action == 'labeled' && github.event.label.name == 'autocoder-bot' ||
      contains(join(github.event.issue.labels.*.name, ','), 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Environment
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Make script executable
        run: chmod +x ./scripts/script.sh

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          ./scripts/script.sh "$GITHUB_TOKEN" "$REPOSITORY" "$ISSUE_NUMBER" "$OPENAI_API_KEY"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact

      - name: Display Generated Files
        run: |
          echo "Listing contents of autocoder-artifact directory:"
          ls -R autocoder-artifact
